vector<tuple<string, string>> armReplacements = {
{ "_memcpy", "replace_memcpy" }, 
{ "_memset", "replace_memset" }, 
{ "_memmove", "replace_memmove" }, 
{ "__swift_stdlib_operatingSystemVersion", "replace__swift_stdlib_operatingSystemVersion" }, 
{ "_asl_log", "replace_asl_log" }, 
{ "_asl_vlog", "replace_asl_vlog" }, 
{ "_CFStringCreateWithFormatAndArguments", "replace_CFStringCreateWithFormatAndArguments" }, 
{ "_printf", "replace_printf" }, 
{ "_sprintf", "replace_sprintf" }, 
{ "___sprintf_chk", "replace___sprintf_chk" }, 
{ "_snprintf", "replace_snprintf" }, 
{ "___snprintf_chk", "replace___snprintf_chk" }, 
{ "_vprintf", "replace_vprintf" }, 
{ "_vsnprintf", "replace_vsnprintf" }, 
{ "___vsnprintf_chk", "replace___vsnprintf_chk" }, 
{ "_fprintf", "replace_fprintf" }, 
{ "_vfprintf", "replace_vfprintf" }, 
{ "_vasprintf", "replace_vasprintf" }, 
{ "_NSLogv", "replace_NSLogv" }, 
{ "_NSLog", "replace_NSLog" }, 
};
vector<tuple<const char*, const char*>> armSelReplacements = {
{ "arrayWithObjects:", "replace_arrayWithObjects_" }, 
{ "setWithObjects:", "replace_setWithObjects_" }, 
{ "dictionaryWithObjectsAndKeys:", "replace_dictionaryWithObjectsAndKeys_" }, 
{ "initWithObjectsAndKeys:", "replace_initWithObjectsAndKeys_" }, 
{ "initWithObjects:", "replace_initWithObjects_" }, 
{ "initWithFormat:", "replace_initWithFormat_" }, 
{ "initWithFormat:arguments:", "replace_initWithFormat_arguments_" }, 
{ "deferredLocalizedIntentsStringWithFormat:", "replace_deferredLocalizedIntentsStringWithFormat_" }, 
{ "initWithFormat:locale:", "replace_initWithFormat_locale_" }, 
{ "initWithFormat:locale:arguments:", "replace_initWithFormat_locale_arguments_" }, 
{ "stringByAppendingFormat:", "replace_stringByAppendingFormat_" }, 
{ "appendFormat:", "replace_appendFormat_" }, 
{ "stringWithFormat:", "replace_stringWithFormat_" }, 
{ "predicateWithFormat:arguments:", "replace_predicateWithFormat_arguments_" }, 
{ "predicateWithFormat:", "replace_predicateWithFormat_" }, 
};
